import {
  SESSION_DECK_ITERM2_TOOL_DISPLAY_NAME,
  SESSION_DECK_ITERM2_TOOL_IDENTIFIER,
} from './paths.js';

export interface RenderSessionDeckIterm2PythonScriptOptions {
  helperScriptPath: string;
  nodeExecutablePath: string;
  packageVersion: string;
  webRootPath: string;
}

export function renderSessionDeckIterm2PythonScript(
  options: RenderSessionDeckIterm2PythonScriptOptions,
): string {
  const helperScriptPath = toPythonString(options.helperScriptPath);
  const nodeExecutablePath = toPythonString(options.nodeExecutablePath);
  const packageVersion = toPythonString(options.packageVersion);
  const webRootPath = toPythonString(options.webRootPath);
  const toolDisplayName = toPythonString(SESSION_DECK_ITERM2_TOOL_DISPLAY_NAME);
  const toolIdentifier = toPythonString(SESSION_DECK_ITERM2_TOOL_IDENTIFIER);

  return `#!/usr/bin/env python3
# Generated by @robhowley/pi-session-deck. Do not edit.
# session-deck-iterm2-owner: true

import json
import os
import posixpath
import subprocess
import threading
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse

import iterm2

HOST = "127.0.0.1"
NODE_EXECUTABLE = ${nodeExecutablePath}
SNAPSHOT_HELPER_PATH = ${helperScriptPath}
WEB_ROOT = ${webRootPath}
PACKAGE_VERSION = ${packageVersion}
TOOL_DISPLAY_NAME = ${toolDisplayName}
TOOL_IDENTIFIER = ${toolIdentifier}
SNAPSHOT_ERROR_CODE = "toolbelt_snapshot_unavailable"

STATIC_CONTENT_TYPES = {
    ".css": "text/css; charset=utf-8",
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
}

STARTED_AT = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def empty_snapshot(message: str):
    return {
        "generatedAt": utc_now_iso(),
        "records": [],
        "diagnostics": [
            {
                "code": SNAPSHOT_ERROR_CODE,
                "message": message,
            }
        ],
    }


def read_snapshot():
    if not os.path.exists(SNAPSHOT_HELPER_PATH):
        return empty_snapshot(f"Snapshot helper not found: {SNAPSHOT_HELPER_PATH}")

    try:
        completed = subprocess.run(
            [NODE_EXECUTABLE, SNAPSHOT_HELPER_PATH],
            capture_output=True,
            check=False,
            text=True,
            timeout=10,
        )
    except Exception as exc:
        return empty_snapshot(f"Could not run snapshot helper: {exc}")

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or f"exit {completed.returncode}").strip()
        return empty_snapshot(f"Snapshot helper failed: {detail}")

    try:
        payload = json.loads(completed.stdout)
    except Exception as exc:
        return empty_snapshot(f"Snapshot JSON is invalid: {exc}")

    if not isinstance(payload, dict):
        return empty_snapshot("Snapshot root is not an object")

    return payload


def resolve_static_path(pathname: str):
    normalized = "/index.html" if pathname in ("", "/") else pathname
    normalized = posixpath.normpath(normalized)
    if normalized.startswith("../") or "/../" in normalized:
        return None

    candidate = os.path.realpath(os.path.join(WEB_ROOT, normalized.lstrip("/")))
    web_root = os.path.realpath(WEB_ROOT)
    if candidate != web_root and not candidate.startswith(web_root + os.sep):
        return None

    return candidate


class SessionDeckToolbeltHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        parsed = urlparse(self.path)
        pathname = parsed.path

        if pathname == "/snapshot.json":
            self.send_json(200, read_snapshot())
            return

        if pathname == "/healthz":
            self.send_json(
                200,
                {
                    "service": TOOL_IDENTIFIER,
                    "pid": os.getpid(),
                    "port": self.server.server_address[1],
                    "startedAt": STARTED_AT,
                    "packageVersion": PACKAGE_VERSION,
                    "helperScriptPath": SNAPSHOT_HELPER_PATH,
                    "webRoot": WEB_ROOT,
                },
            )
            return

        static_path = resolve_static_path(pathname)
        if static_path is None or not os.path.exists(static_path):
            self.send_text(404, "Not found")
            return

        extension = os.path.splitext(static_path)[1]
        content_type = STATIC_CONTENT_TYPES.get(extension)
        if content_type is None:
            self.send_text(404, "Not found")
            return

        try:
            with open(static_path, "rb") as file_handle:
                self.send_bytes(200, content_type, file_handle.read())
        except Exception:
            self.send_text(404, "Not found")

    def log_message(self, format, *args):
        return

    def send_json(self, status_code: int, payload):
        self.send_bytes(status_code, "application/json; charset=utf-8", (json.dumps(payload) + "\n").encode("utf-8"))

    def send_text(self, status_code: int, text: str):
        self.send_bytes(status_code, "text/plain; charset=utf-8", text.encode("utf-8"))

    def send_bytes(self, status_code: int, content_type: str, payload: bytes):
        self.send_response(status_code)
        self.send_header("Cache-Control", "no-store")
        self.send_header(
            "Content-Security-Policy",
            "default-src 'self'; connect-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",
        )
        self.send_header("Content-Type", content_type)
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)


def start_http_server():
    server = ThreadingHTTPServer((HOST, 0), SessionDeckToolbeltHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    return server


async def main(connection):
    server = start_http_server()
    port = server.server_address[1]
    await iterm2.tool.async_register_web_view_tool(
        connection=connection,
        display_name=TOOL_DISPLAY_NAME,
        identifier=TOOL_IDENTIFIER,
        reveal_if_already_registered=True,
        url=f"http://{HOST}:{port}/",
    )


iterm2.run_forever(main)
`;
}

function toPythonString(value: string): string {
  return JSON.stringify(value);
}
